
services:
    db:
        image: postgres:16.0
        container_name: postgres_db
        restart: always
        ports:
          - "5432:5432"
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: django_db
        volumes:
          - postgres_db:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres -d django_db" ]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s

    app:
        build: .
        container_name: django_app
        restart: unless-stopped
        ports:
          - "8000:8000"
        depends_on:
          db:
            condition: service_healthy
        environment:
          DATABASE_NAME: "django_db"
          DATABASE_PASSWORD: "password"
          DATABASE_HOST: "db:5432"

volumes:
  postgres_db: