# Generated by Django 5.2.1 on 2025-05-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=50)),
                ('description', models.CharField(blank=True, null=True, verbose_name=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ot', 'другое'), ('el', 'электроника'), ('cl', 'одежда'), ('fu', 'мебель')], default='ot', verbose_name=2)),
                ('condition', models.CharField(choices=[('ne', 'новый'), ('us', 'б/у')], default='ne', verbose_name=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, null=True, verbose_name=200)),
                ('status', models.CharField(choices=[('wa', 'ожидает'), ('ac', 'принята'), ('de', 'отклонена')], default='wa', verbose_name=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.ad')),
            ],
        ),
    ]
