# Generated by Django 5.2.1 on 2025-05-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('ot', 'другое'), ('el', 'электроника'), ('cl', 'одежда'), ('fu', 'мебель')], default='ot', max_length=2),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('ne', 'новый'), ('us', 'б/у')], default='ne', max_length=2),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('wa', 'ожидает'), ('ac', 'принята'), ('de', 'отклонена')], default='wa', max_length=2),
        ),
    ]
